export const oilData = [
    {
      id: 1,
      title: "زيت زيتون",
      image: "../../images/عسل البردقوش.jpg",
      price: "225",
    },
    {
      id: 2,
      title: "زيت بزر الكتان",
      image: "../../public/oilimages/زيت بذرة الكتان.jpg",
      price: "125",
    },
    {
      id: 3,
      title: "زيت اللوز الحلو",
      image: "../../public/oilimages/زيت اللوز الحلوjpg.jpg",
      price: "250",
    },
    {
      id: 4,
      title: "زيت حبة البركه",
      image: "../../public/oilimages/زيت حبة البركهjpg.jpg",
      price: "200",
    },
    {
      id: 5,
      title: "زيت بزر العنب",
      image: "../../public/oilimages/زيت بذر العنب.jpg",
      price: "250",
    },
    {
      id: 6,
      title: "زيت حبة البركه",
      image: "../../public/oilimages/زيت حبة البركه2.jpg",
      price: "200",
    },
    {
      id: 7,
      title: "زيت وز الهند",
      image: "../../public/oilimages/زيت وز الهند.jpg",
      price: "150",
    },
    {
      id: 8,
      title: "زيت وز الهند",
      image: "../../public/oilimages/زيت وز الهند2.jpg",
      price: "150",
    },
    {
      id: 9,
      title: "زيت حبة البركه",
      image: "../../public/oilimages/زيت حبة البركه 3.jpg",
      price: "200",
    },
    {
      id: 10,
      title: "زيت وز الهند",
      image: "../../public/oilimages/زيت وز الهند3.jpg",
      price: "150",
    },
    {
      id: 11,
      title: "زيت حبة البركه",
      image: "../../public/oilimages/زيت حبة البركه 3.jpg",
      price: "200",
    },
  ];
  
  export const honeyData = [
    {
      id: 1,
      title: "عسل صدر مصري",
      image: "/static/media/عسل صدر جبلي.5065cd489736d26db622.jpg",
      price: "160",
    },
    {
      id: 3,
      title: "عسل حبة البركه 1000م",
      image: "/static/media/عسل حبة البركه.7cf6cd89f8049435d0e7.jpg",
      price: "180",
    },
    {
      id: 4,
      title: "عسل بردقوش",
      image: "/static/media/عسل%20البردقوش.e168986583b9dbc546f3.jpg",
      price: "185",
    },
    {
      id: 5,
      title: "عسل المورينا",
      image: "",
      price: "73",
    },
    {
      id: 6,
      title: "عسل بردقوش",
      image: "",
      price: "185",
    },
    {
      id: 7,
      title: "عسل زهور الربيع + لانش بوكس",
      image: "",
      price: "164.50",
    },
    {
      id: 8,
      title: "عسل بالمكسرات500م",
      image: "",
      price: "160",
    },
    {
      id: 10,
      title: "شمع بالعسل",
      image: "",
      price: "140",
    },
    {
      id: 12,
      title: "عسل زهور الربيع",
      image: "",
      price: "671",
    },
    {
      id: 13,
      title: "عسل سعودي(سدر بلي)",
      image: "",
      price: "1000",
    },
    {
      id: 14,
      title: "عسل بردقوش",
      image: "",
      price: "95",
    },
    {
      id: 15,
      title: "عسل دوعني",
      image: "",
      price: "1200",
    },
    {
      id: 16,
      title: "عسل كريمي بغزاءالملكات",
      image: "",
      price: "1600",
    },
    {
      id: 17,
      title: "عسل حضرمي",
      image: "",
      price: "1150",
    },
    {
      id: 18,
      title: "عسل زهور الربيع + البردقوش",
      image: "",
      price: "164.50",
    },
    {
      id: 19,
      title: "عسل زهور الربيع + حبةالبركه",
      image: "",
      price: "164.50",
    },
    {
      id: 20,
      title: "عسل البرسيم + حبةالبركه",
      image: "",
      price: "164.50",
    },
    {
      id: 21,
      title: "عسل النكة",
      image: "",
      price: "73",
    },
    {
      id: 22,
      title: "عسل زهرة الشوك",
      image: "",
      price: "81",
    },
    {
      id: 23,
      title: "عسل حبة البركه",
      image: "",
      price: "74.50",
    },
    {
      id: 24,
      title: "عسل بعين المل",
      image: "",
      price: "155",
    },
    {
      id: 25,
      title: "عسل فستق ايراني",
      image: "",
      price: "228",
    },
    {
      id: 26,
      title: "شمع عسل",
      image: "",
      price: "273.50",
    },
    {
      id: 27,
      title: "عسل بالمكسرات",
      image: "",
      price: "271",
    },
    {
      id: 28,
      title: "عسل الاخناسيا",
      image: "",
      price: "90",
    },
    {
      id: 29,
      title: "عسل البردقوش",
      image: "",
      price: "108",
    },
    {
      id: 30,
      title: "عسل زهور برية",
      image: "",
      price: "289",
    },
    {
      id: 31,
      title: "عسل النباتات الطبيه",
      image: "",
      price: "98.50",
    },
    {
      id: 32,
      title: "عسل زهور اسبانيا",
      image: "",
      price: "207.50",
    },
    {
      id: 33,
      title: "عسل زهور الموالح",
      image: "",
      price: "73",
    },
    {
      id: 34,
      title: "عسل حبة البركه",
      image: "",
      price: "73",
    },
    {
      id: 35,
      title: "عسل زهور النوب",
      image: "",
      price: "164.50",
    },
    {
      id: 36,
      title: "عسل خبز النحل ",
      image: "",
      price: "122",
    },
    {
      id: 37,
      title: "عسل بي اميون",
      image: "",
      price: "235",
    },
    {
      id: 38,
      title: "عسل البرسيم",
      image: "",
      price: "787",
    },
    {
      id: 39,
      title: "عسل سوبر اميون بالفانيليا",
      image: "",
      price: "149",
    },
    {
      id: 40,
      title: "عسل سوبر اميون بالشيكولاتة",
      image: "",
      price: "149",
    },
    {
      id: 41,
      title: "عسل الينسين",
      image: "",
      price: "217",
    },
    {
      id: 42,
      title: "عسل سدر بلي مصري",
      image: "",
      price: "1288",
    },
    {
      id: 43,
      title: "عسل سدر بلي كشميري",
      image: "",
      price: "2685",
    },
    {
      id: 44,
      title: "عسل سدر بلي خضرمي",
      image: "",
      price: "3860",
    },
  ];
  
  export const herbalData = [
    {
      id: 1,
      title: "ورق سدر مفف ٥۰ م",
      image: "../../public/herbal images/sider.png",
      price: "15",
    },
    {
      id: 2,
      title: "ورق الاس ۹۰ م",
      image: "../../public/herbal images/ass-paperpng.png",
      price: "15",
    },
    {
      id: 3,
      title: "عرعر مفف ۹۰ م",
      image: "../../public/herbal images/arar.jpg",
      price: "15",
    },
    {
      id: 4,
      title: "ملب النفاس ۱ كيلو ",
      image: "../../public/herbal images/mglb-nfas.jpg",
      price: "15",
    },
    {
      id: 5,
      title: "حبق مفف ٥۰ م ",
      image: "../../public/herbal images/hobok.jpg",
      price: "15",
    },
    {
      id: 6,
      title: "    ورق الوافه ۸۰",
      image: "../../public/herbal images/gawafa.png",
      price: "15",
    },
    {
      id: 7,
      title: "اكليل البل ( رزوماري ) ۱۲٥ م",
      image: "../../public/herbal images/iklil-algabal.jpg",
      price: "15",
    },
    {
      id: 8,
      title: "اسبيغول ۲۰۰ م ",
      image: "../../public/herbal images/isbeghol.png",
      price: "15",
    },
    {
      id: 9,
      title: "ورق محمدي ٥۰ م  ",
      image: "../../public/herbal images/mohamedy-paper.png",
      price: "15",
    },
    {
      id: 10,
      title: "ورق النيم",
      image: "../../public/herbal images/neem-paper.png",
      price: "15",
    },
    {
      id: 11,
      title: "ورق زعتر  ",
      image: "../../public/herbal images/zater-paper.jpg",
      price: "15",
    },
    {
      id: 12,
      title: " شيكاكاي ۱۲۰ م ",
      image: "../../public/herbal images/shikaki.jpg",
      price: "15",
    },
    {
      id: 13,
      title: " ميرمية ",
      image: "../../public/herbal images/mirmia.jpg",
      price: "15",
    },
    {
      id: 14,
      title: " زعفران أبو شيبه فاخر ۲ م ",
      image: "../../public/herbal images/zafran-shiba.png",
      price: "15",
    },
    {
      id: 15,
      title: "  ورق وسمه ۱٥۰ م  ",
      image: "../../public/herbal images/wasma-paper.jpg",
      price: "15",
    },
    {
      id: 16,
      title: "القسط الهندي ۱۲٥ م ",
      image: "../../public/herbal images/indian-kist.png",
      price: "15",
    },
    {
      id: 17,
      title: "  قرفه سبلاني ۱٥۰ م ",
      image: "../../public/herbal images/krfa.png",
      price: "15",
    },
    {
      id: 18,
      title: " قرنفل ۲٥۰ م    ",
      image: "../../public/herbal images/kronfeljpg.jpg",
      price: "15",
    },
    {
      id: 19,
      title: "  خزامى / لافندر ٦۰ م    ",
      image: "../../public/herbal images/lavander.png",
      price: "15",
    },
    {
      id: 20,
      title: " بابون ۱۲۰ م ",
      image: "../../public/herbal images/babongjpg.jpg",
      price: "15",
    },
    {
      id: 21,
      title: " مورينا ۷٥ م     ",
      image: "../../public/herbal images/moringa.jpg",
      price: "15",
    },
    {
      id: 22,
      title: "   وسمه ( ناعم ) ۱۲٥ م ",
      image: "../../public/herbal images/smoth-wasma.png",
      price: "15",
    },
    {
      id: 23,
      title: "  ورق سنا ( سنامكي )  ",
      image: "../../public/herbal images/sanamaki-paper.png",
      price: "15",
    },
  ];
  