export const oilData = [
  {
    id: 1,
    title: "زيت زيتون",
    Image: "../../images/عسل البردقوش.jpg",
    price: "225"
  },
  {
    id: 2,
    title: "زيت بزر الكتان",
    Image: "../../public/oilImages/زيت بذرة الكتان.jpg",
    price: "125",
  },
  {
    id: 3,
    title: "زيت اللوز الحلو",
    Image: "../../public/oilImages/زيت اللوز الحلوjpg.jpg",
    price: "250",
  },
  {
    id: 4,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركهjpg.jpg",
    price: "200",
  },
  {
    id: 5,
    title: "زيت بزر العنب",
    Image: "../../public/oilImages/زيت بذر العنب.jpg",
    price: "250",
  },
  {
    id: 6,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركه2.jpg",
    price: "200",
  },
  {
    id: 7,
    title: "زيت وز الهند",
    Image: "../../public/oilImages/زيت وز الهند.jpg",
    price: "150",
  },
  {
    id: 8,
    title: "زيت وز الهند",
    Image: "../../public/oilImages/زيت وز الهند2.jpg",
    price: "150",
  },
  {
    id: 9,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركه 3.jpg",
    price: "200",
  },
  {
    id: 10,
    title: "زيت وز الهند",
    Image: "../../public/oilImages/زيت وز الهند3.jpg",
    price: "150",
  },
  {
    id: 11,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركه 3.jpg",
    price: "200",
  },
];

export const honeyData = [
  {
    id: 1,
    title: "عسل صدر مصري",
    Image: "/static/media/عسل صدر جبلي.5065cd489736d26db622.jpg",
    price: "160",
  },
  {
    id: 3,
    title: "عسل حبة البركه 1000م",
    Image: "/static/media/عسل حبة البركه.7cf6cd89f8049435d0e7.jpg",
    price: "180",
  },
  {
    id: 4,
    title: "عسل بردقوش",
    Image: "/static/media/عسل%20البردقوش.e168986583b9dbc546f3.jpg",
    price: "185",
  },
  {
    id: 5,
    title: "عسل المورينا",
    Image: "",
    price: "73",
  },
  {
    id: 6,
    title: "عسل بردقوش",
    Image: "",
    price: "185",
  },
  {
    id: 7,
    title: "عسل زهور الربيع + لانش بوكس",
    Image: "",
    price: "164.50",
  },
  {
    id: 8,
    title: "عسل بالمكسرات500م",
    Image: "",
    price: "160",
  },
  {
    id: 10,
    title: "شمع بالعسل",
    Image: "",
    price: "140",
  },
  {
    id: 12,
    title: "عسل زهور الربيع",
    Image: "",
    price: "671",
  },
  {
    id: 13,
    title: "عسل سعودي(سدر بلي)",
    Image: "",
    price: "1000",
  },
  {
    id: 14,
    title: "عسل بردقوش",
    Image: "",
    price: "95",
  },
  {
    id: 15,
    title: "عسل دوعني",
    Image: "",
    price: "1200",
  },
  {
    id: 16,
    title: "عسل كريمي بغزاءالملكات",
    Image: "",
    price: "1600",
  },
  {
    id: 17,
    title: "عسل حضرمي",
    Image: "",
    price: "1150",
  },
  {
    id: 18,
    title: "عسل زهور الربيع + البردقوش",
    Image: "",
    price: "164.50",
  },
  {
    id: 19,
    title: "عسل زهور الربيع + حبةالبركه",
    Image: "",
    price: "164.50",
  },
  {
    id: 20,
    title: "عسل البرسيم + حبةالبركه",
    Image: "",
    price: "164.50",
  },
  {
    id: 21,
    title: "عسل النكة",
    Image: "",
    price: "73",
  },
  {
    id: 22,
    title: "عسل زهرة الشوك",
    Image: "",
    price: "81",
  },
  {
    id: 23,
    title: "عسل حبة البركه",
    Image: "",
    price: "74.50",
  },
  {
    id: 24,
    title: "عسل بعين المل",
    Image: "",
    price: "155",
  },
  {
    id: 25,
    title: "عسل فستق ايراني",
    Image: "",
    price: "228",
  },
  {
    id: 26,
    title: "شمع عسل",
    Image: "",
    price: "273.50",
  },
  {
    id: 27,
    title: "عسل بالمكسرات",
    Image: "",
    price: "271",
  },
  {
    id: 28,
    title: "عسل الاخناسيا",
    Image: "",
    price: "90",
  },
  {
    id: 29,
    title: "عسل البردقوش",
    Image: "",
    price: "108",
  },
  {
    id: 30,
    title: "عسل زهور برية",
    Image: "",
    price: "289",
  },
  {
    id: 31,
    title: "عسل النباتات الطبيه",
    Image: "",
    price: "98.50",
  },
  {
    id: 32,
    title: "عسل زهور اسبانيا",
    Image: "",
    price: "207.50",
  },
  {
    id: 33,
    title: "عسل زهور الموالح",
    Image: "",
    price: "73",
  },
  {
    id: 34,
    title: "عسل حبة البركه",
    Image: "",
    price: "73",
  },
  {
    id: 35,
    title: "عسل زهور النوب",
    Image: "",
    price: "164.50",
  },
  {
    id: 36,
    title: "عسل خبز النحل ",
    Image: "",
    price: "122",
  },
  {
    id: 37,
    title: "عسل بي اميون",
    Image: "",
    price: "235",
  },
  {
    id: 38,
    title: "عسل البرسيم",
    Image: "",
    price: "787",
  },
  {
    id: 39,
    title: "عسل سوبر اميون بالفانيليا",
    Image: "",
    price: "149",
  },
  {
    id: 40,
    title: "عسل سوبر اميون بالشيكولاتة",
    Image: "",
    price: "149",
  },
  {
    id: 41,
    title: "عسل الينسين",
    Image: "",
    price: "217",
  },
  {
    id: 42,
    title: "عسل سدر بلي مصري",
    Image: "",
    price: "1288",
  },
  {
    id: 43,
    title: "عسل سدر بلي كشميري",
    Image: "",
    price: "2685",
  },
  {
    id: 44,
    title: "عسل سدر بلي خضرمي",
    Image: "",
    price: "3860",
  },
];

export const herbalData = [
  {
    id: 1,
    title: "ورق سدر مفف ٥۰ م",
    Image: "../../public/herbal images/sider.png",
    price: "15",
  },
  {
    id: 2,
    title: "ورق الاس ۹۰ م",
    Image: "../../public/herbal images/ass-paperpng.png",
    price: "15",
  },
  {
    id: 3,
    title: "عرعر مفف ۹۰ م",
    Image: "../../public/herbal images/arar.jpg",
    price: "15",
  },
  {
    id: 4,
    title: "ملب النفاس ۱ كيلو ",
    Image: "../../public/herbal images/mglb-nfas.jpg",
    price: "15",
  },
  {
    id: 5,
    title: "حبق مفف ٥۰ م ",
    Image: "../../public/herbal images/hobok.jpg",
    price: "15",
  },
  {
    id: 6,
    title: "    ورق الوافه ۸۰",
    Image: "../../public/herbal images/gawafa.png",
    price: "15",
  },
  {
    id: 7,
    title: "اكليل البل ( رزوماري ) ۱۲٥ م",
    Image: "../../public/herbal images/iklil-algabal.jpg",
    price: "15",
  },
  {
    id: 8,
    title: "اسبيغول ۲۰۰ م ",
    Image: "../../public/herbal images/isbeghol.png",
    price: "15",
  },
  {
    id: 9,
    title: "ورق محمدي ٥۰ م  ",
    Image: "../../public/herbal images/mohamedy-paper.png",
    price: "15",
  },
  {
    id: 10,
    title: "ورق النيم",
    Image: "../../public/herbal images/neem-paper.png",
    price: "15",
  },
  {
    id: 11,
    title: "ورق زعتر  ",
    Image: "../../public/herbal images/zater-paper.jpg",
    price: "15",
  },
  {
    id: 12,
    title: " شيكاكاي ۱۲۰ م ",
    Image: "../../public/herbal images/shikaki.jpg",
    price: "15",
  },
  {
    id: 13,
    title: " ميرمية ",
    Image: "../../public/herbal images/mirmia.jpg",
    price: "15",
  },
  {
    id: 14,
    title: " زعفران أبو شيبه فاخر ۲ م ",
    Image: "../../public/herbal images/zafran-shiba.png",
    price: "15",
  },
  {
    id: 15,
    title: "  ورق وسمه ۱٥۰ م  ",
    Image: "../../public/herbal images/wasma-paper.jpg",
    price: "15",
  },
  {
    id: 16,
    title: "القسط الهندي ۱۲٥ م ",
    Image: "../../public/herbal images/indian-kist.png",
    price: "15",
  },
  {
    id: 17,
    title: "  قرفه سبلاني ۱٥۰ م ",
    Image: "../../public/herbal images/krfa.png",
    price: "15",
  },
  {
    id: 18,
    title: " قرنفل ۲٥۰ م    ",
    Image: "../../public/herbal images/kronfeljpg.jpg",
    price: "15",
  },
  {
    id: 19,
    title: "  خزامى / لافندر ٦۰ م    ",
    Image: "../../public/herbal images/lavander.png",
    price: "15",
  },
  {
    id: 20,
    title: " بابون ۱۲۰ م ",
    Image: "../../public/herbal images/babongjpg.jpg",
    price: "15",
  },
  {
    id: 21,
    title: " مورينا ۷٥ م     ",
    Image: "../../public/herbal images/moringa.jpg",
    price: "15",
  },
  {
    id: 22,
    title: "   وسمه ( ناعم ) ۱۲٥ م ",
    Image: "../../public/herbal images/smoth-wasma.png",
    price: "15",
  },
  {
    id: 23,
    title: "  ورق سنا ( سنامكي )  ",
    Image: "../../public/herbal images/sanamaki-paper.png",
    price: "15",
  },
];
